# Generated by Django 6.0.2 on 2026-02-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='pension_month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Setiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='proof_image',
            field=models.FileField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='concept',
            field=models.CharField(choices=[('matricula', 'Matricula'), ('pension', 'Pension'), ('material_escolar', 'Material escolar'), ('libro', 'Libro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('yape_plin', 'Yape/Plin')], default='cash', max_length=20),
        ),
    ]
