# Generated by Django 6.0.2 on 2026-02-19 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_course_book_price'),
        ('finance', '0002_fee_pension_month_payment_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.course', verbose_name='Curso (para libros)'),
        ),
    ]
