# Generated by Django 6.0.2 on 2026-02-25 06:36

from decimal import Decimal
from django.db import migrations, models


def sync_fee_paid_and_status(apps, schema_editor):
    Fee = apps.get_model('finance', 'Fee')
    Payment = apps.get_model('finance', 'Payment')

    for fee in Fee.objects.all():
        total_paid = Payment.objects.filter(fee_id=fee.id).aggregate(total=models.Sum('amount'))['total'] or Decimal('0.00')
        if total_paid >= fee.amount:
            status = 'paid'
            if total_paid > fee.amount:
                total_paid = fee.amount
        elif total_paid > Decimal('0.00'):
            status = 'partial'
        else:
            status = 'pending'

        fee.amount_paid = total_paid
        fee.status = status
        fee.save(update_fields=['amount_paid', 'status'])


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_fee_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='fee',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('partial', 'Parcial'), ('paid', 'Pagado')], default='pending', max_length=20),
        ),
        migrations.RunPython(sync_fee_paid_and_status, migrations.RunPython.noop),
    ]
