# Generated by Django 6.0.2 on 2026-02-26 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_fee_amount_paid_alter_fee_status'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='inventory_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees', to='inventory.product', verbose_name='Producto de inventario'),
        ),
        migrations.AddField(
            model_name='fee',
            name='inventory_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad vendida'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='concept',
            field=models.CharField(choices=[('matricula', 'Matricula'), ('pension', 'Pension'), ('material_escolar', 'Material escolar'), ('libro', 'Libro'), ('producto_inventario', 'Producto de inventario')], max_length=30),
        ),
    ]
