# Generated by Django 6.0.2 on 2026-02-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_fee_inventory_product_fee_inventory_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='concept',
            field=models.CharField(choices=[('matricula', 'Matricula'), ('pension', 'Pension'), ('material_escolar', 'Material escolar'), ('libro', 'Libro'), ('uniforme_banda', 'Uniforme de Banda'), ('uniforme_colegio', 'Uniforme del Colegio'), ('producto_inventario', 'Producto de inventario')], max_length=30),
        ),
    ]
