# Generated by Django 6.0.2 on 2026-02-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('director', 'Director'), ('teacher', 'Docente'), ('secretary', 'Secretaria'), ('parent', 'Padre')], max_length=20),
        ),
    ]
