# Generated by Django 6.0.2 on 2026-02-19 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_competency_indicator_indicatorgrade'),
        ('accounts', '0003_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teaching_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='academic.grade'),
        ),
    ]
