# Generated by Django 6.0.2 on 2026-02-19 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_level_alter_grade_options_alter_period_options_and_more'),
        ('accounts', '0004_user_teaching_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teaching_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers_by_level', to='academic.level'),
        ),
        migrations.AddField(
            model_name='user',
            name='teaching_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers_by_section', to='academic.section'),
        ),
    ]
