# Generated by Django 6.0.2 on 2026-02-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_level_alter_grade_options_alter_period_options_and_more'),
        ('accounts', '0005_user_teaching_level_user_teaching_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='teaching_level',
        ),
        migrations.AddField(
            model_name='user',
            name='is_polyteacher',
            field=models.BooleanField(default=False, verbose_name='Es polidocente'),
        ),
        migrations.AddField(
            model_name='user',
            name='teaching_courses',
            field=models.ManyToManyField(blank=True, related_name='poly_teachers', to='academic.course', verbose_name='Cursos que enseña (polidocente)'),
        ),
        migrations.AddField(
            model_name='user',
            name='teaching_grades',
            field=models.ManyToManyField(blank=True, related_name='poly_teachers_grades', to='academic.grade', verbose_name='Grados que enseña (polidocente)'),
        ),
    ]
