# Generated by Django 6.0.2 on 2026-02-22 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_course_book_price'),
        ('accounts', '0007_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='poly_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poly_teachers_assigned', to='academic.course', verbose_name='Curso de polidocencia'),
        ),
        migrations.AlterField(
            model_name='user',
            name='teaching_courses',
            field=models.ManyToManyField(blank=True, related_name='poly_teachers', to='academic.course', verbose_name='Cursos que enseña (polidocente) - MÚLTIPLES'),
        ),
    ]
