# Generated by Django 6.0.2 on 2026-02-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_course_is_poly_course'),
        ('accounts', '0008_user_poly_course_alter_user_teaching_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teaching_sections',
            field=models.ManyToManyField(blank=True, related_name='poly_teachers_sections', to='academic.section', verbose_name='Secciones que enseña (polidocente)'),
        ),
    ]
