# Generated by Django 6.0.2 on 2026-03-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0017_course_grades'),
        ('accounts', '0009_user_teaching_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='teaching_courses',
            field=models.ManyToManyField(blank=True, related_name='poly_teachers', to='academic.course', verbose_name='Cursos que ensena (polidocente) - MULTIPLES'),
        ),
        migrations.AlterField(
            model_name='user',
            name='teaching_grades',
            field=models.ManyToManyField(blank=True, related_name='poly_teachers_grades', to='academic.grade', verbose_name='Grados que ensena (polidocente)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='teaching_sections',
            field=models.ManyToManyField(blank=True, related_name='poly_teachers_sections', to='academic.section', verbose_name='Secciones que ensena (polidocente)'),
        ),
    ]
