# Generated by Django 6.0.2 on 2026-02-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_graderecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graderecord',
            name='score',
        ),
        migrations.AddField(
            model_name='graderecord',
            name='grade',
            field=models.CharField(choices=[('AD', 'Logro Destacado'), ('A', 'Logro Esperado'), ('B', 'En Proceso'), ('C', 'En Inicio')], default='A', max_length=2),
            preserve_default=False,
        ),
    ]
