# Generated by Django 6.0.2 on 2026-02-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_remove_graderecord_score_graderecord_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graderecord',
            name='grade',
            field=models.CharField(choices=[('AD', 'AD'), ('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=2),
        ),
    ]
