# Generated by Django 6.0.2 on 2026-02-18 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_alter_graderecord_unique_together_and_more'),
        ('enrollment', '0002_alter_enrollment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.course')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=1)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.competency')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='IndicatorGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('AD', 'AD'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=2)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.enrollment')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.indicator')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.period')),
            ],
            options={
                'unique_together': {('enrollment', 'indicator', 'period')},
            },
        ),
    ]
