# Generated by Django 6.0.2 on 2026-02-19 05:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


def seed_academic_structure(apps, schema_editor):
    Level = apps.get_model('academic', 'Level')
    Grade = apps.get_model('academic', 'Grade')
    Period = apps.get_model('academic', 'Period')
    TeacherCourseAssignment = apps.get_model('academic', 'TeacherCourseAssignment')

    default_level, _ = Level.objects.get_or_create(name='General')
    Grade.objects.filter(level__isnull=True).update(level=default_level)

    for assignment in TeacherCourseAssignment.objects.select_related('section__grade').all():
        grade = assignment.section.grade if assignment.section_id else None
        level = grade.level if grade else None
        updates = []
        if grade and assignment.grade_id != grade.id:
            assignment.grade_id = grade.id
            updates.append('grade')
        if level and assignment.level_id != level.id:
            assignment.level_id = level.id
            updates.append('level')
        if updates:
            assignment.save(update_fields=updates)

    for period in Period.objects.select_related('academic_year').all():
        updates = []
        if period.start_date is None:
            period.start_date = datetime.date(period.academic_year.year, 1, 1)
            updates.append('start_date')
        if period.end_date is None:
            period.end_date = datetime.date(period.academic_year.year, 12, 31)
            updates.append('end_date')
        if updates:
            period.save(update_fields=updates)

    if not Period.objects.filter(is_active=True).exists():
        first_period = Period.objects.order_by('-academic_year__year', 'start_date', 'id').first()
        if first_period:
            first_period.is_active = True
            first_period.save(update_fields=['is_active'])


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_competency_indicator_indicatorgrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ('-academic_year__year', 'start_date', 'name')},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('grade__name', 'name')},
        ),
        migrations.AlterModelOptions(
            name='teachercourseassignment',
            options={'ordering': ('academic_year__year', 'level__name', 'grade__name', 'section__name', 'course__name')},
        ),
        migrations.AddField(
            model_name='period',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='period',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='period',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='teachercourseassignment',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.grade'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('grade', 'name')},
        ),
        migrations.AddField(
            model_name='grade',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='academic.level'),
        ),
        migrations.AddField(
            model_name='teachercourseassignment',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.level'),
        ),
        migrations.RunPython(seed_academic_structure, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_period'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(fields=('academic_year', 'name'), name='unique_period_name_per_year'),
        ),
    ]
