# Generated by Django 6.0.2 on 2026-02-19 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_level_alter_grade_options_alter_period_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachercourseassignment',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.section'),
        ),
    ]
