# Generated by Django 6.0.2 on 2026-02-19 18:16

from django.db import migrations


def remove_general_level(apps, schema_editor):
    Level = apps.get_model('academic', 'Level')
    Level.objects.filter(name='General').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_alter_teachercourseassignment_section'),
    ]

    operations = [
        migrations.RunPython(remove_general_level),
    ]
