# Generated by Django 6.0.2 on 2026-02-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_remove_general_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='book_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio del Libro'),
        ),
    ]
