# Generated by Django 6.0.2 on 2026-02-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_course_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_poly_course',
            field=models.BooleanField(default=False, verbose_name='¿Es curso de polidocencia?'),
        ),
    ]
