# Generated by Django 6.0.2 on 2026-02-23 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_course_is_poly_course'),
        ('accounts', '0006_remove_user_teaching_level_user_is_polyteacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachercourseassignment',
            name='level',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='level',
        ),
        migrations.AlterModelOptions(
            name='teachercourseassignment',
            options={'ordering': ('academic_year__year', 'grade__name', 'section__name', 'course__name')},
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
