# Generated by Django 6.0.2 on 2026-02-24 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_remove_teachercourseassignment_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='has_book',
            field=models.BooleanField(default=False, verbose_name='Tiene libro'),
        ),
        migrations.AddField(
            model_name='section',
            name='tutor_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_sections', to=settings.AUTH_USER_MODEL, verbose_name='Tutora de aula'),
        ),
    ]
