# Generated by Django 6.0.2 on 2026-02-26 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0014_course_has_book_section_tutor_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='book_price',
        ),
        migrations.RemoveField(
            model_name='course',
            name='has_book',
        ),
    ]
