# Generated by Django 6.0.2 on 2026-03-04 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0015_remove_course_book_price_remove_course_has_book'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeSubmissionLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_locked', models.BooleanField(default=False, verbose_name='¿Bloqueado?')),
                ('last_unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.course')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.period')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.section')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bloqueo de Notas',
                'verbose_name_plural': 'Bloqueos de Notas',
                'unique_together': {('teacher', 'course', 'section', 'period')},
            },
        ),
    ]
