# Generated by Django 6.0.2 on 2026-03-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0016_gradesubmissionlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='grades',
            field=models.ManyToManyField(blank=True, related_name='courses', to='academic.grade', verbose_name='Grados'),
        ),
    ]

