# Generated by Django 6.0.2 on 2026-02-26 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0004_fee_amount_paid_alter_fee_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='ID/Código')),
                ('name', models.CharField(max_length=120, verbose_name='Producto')),
                ('category', models.CharField(choices=[('libro', 'Libro'), ('uniforme_banda', 'Uniforme de Banda'), ('uniforme_colegio', 'Uniforme del Colegio'), ('otro', 'Otro')], default='otro', max_length=30, verbose_name='Categoría')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio (S/)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock actual')),
                ('stock_min', models.PositiveIntegerField(default=5, verbose_name='Stock mínimo')),
                ('stock_max', models.PositiveIntegerField(default=100, verbose_name='Stock máximo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ('category', 'name'),
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida (venta)'), ('ajuste', 'Ajuste')], max_length=20, verbose_name='Tipo')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('previous_stock', models.PositiveIntegerField(verbose_name='Stock anterior')),
                ('new_stock', models.PositiveIntegerField(verbose_name='Stock nuevo')),
                ('reference', models.CharField(blank=True, max_length=120, verbose_name='Referencia/Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='finance.payment', verbose_name='Pago relacionado')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'ordering': ('-created_at',),
            },
        ),
    ]
