# Generated by Django 6.0.2 on 2026-03-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/', verbose_name='Código de Barras'),
        ),
    ]
