# Generated by Django 6.0.2 on 2026-02-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='school_logos/'),
        ),
    ]
