# Generated by Django 6.0.2 on 2026-02-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='enrollment_price',
            field=models.DecimalField(decimal_places=2, default=300.0, max_digits=10, verbose_name='Costo de Matricula'),
        ),
        migrations.AddField(
            model_name='school',
            name='pension_price',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=10, verbose_name='Costo de Pension'),
        ),
        migrations.AddField(
            model_name='school',
            name='supplies_price',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='Costo de Material Escolar'),
        ),
    ]
