# Generated by Django 6.0.2 on 2026-02-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_school_enrollment_price_school_pension_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='ruc',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='RUC'),
        ),
    ]
