# Generated by Django 6.0.2 on 2026-02-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('retired', 'Retirado'), ('transferred', 'Trasladado'), ('finished', 'Finalizado')], default='active', max_length=20),
        ),
    ]
