# Generated by Django 6.0.2 on 2026-02-19 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_level_alter_grade_options_alter_period_options_and_more'),
        ('attendance', '0001_initial'),
        ('enrollment', '0002_alter_enrollment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ('-date', 'assignment__course__name', 'enrollment__student__last_name')},
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academic.teachercourseassignment'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Asistio'), ('absent', 'Falto'), ('justified', 'Justificado')], default='present', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('enrollment', 'date', 'assignment')},
        ),
    ]
