# Generated by Django 6.0.2 on 2026-02-25 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendancerecord_options_and_more'),
        ('enrollment', '0002_alter_enrollment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ('-date', 'enrollment__section__grade__name', 'enrollment__section__name', 'enrollment__student__last_name')},
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('enrollment', 'date')},
        ),
    ]
